name: Create Pull Requests to Main

on:
  push:
    branches: [ "[0-9]+.[0-9]+.[0-9]+", "release/**" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ${{ vars.OS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        shell: bash
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Check if PR exists
        shell: bash
        run: |
          PR_EXISTS=$(gh pr list --state open --head "${{ env.BRANCH_NAME }}" --json number -q '.[].number')
          if [ -z "$PR_EXISTS" ]; then
            echo "Creating PR to main."
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          else
            echo "PR already exists, skipping creation."
            echo "PR_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request to main
        if: env.PR_EXISTS == 'false'
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          PR_TITLE="Merge ${{ env.BRANCH_NAME }} into main"
          gh pr create --base main --head "${{ env.BRANCH_NAME }}" --title "$PR_TITLE" --body "This PR is automatically created from the release branch to the main branch."

  pylint:
    name: Pylint
    needs: create-pr
    runs-on: ${{ vars.OS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyse code
        run: |
          pylint --max-line-length=120 --disable=missing-module-docstring,missing-function-docstring,invalid-name,broad-exception-caught,broad-exception-raised,raise-missing-from $(git ls-files '*.py')
