name: Create Pull Requests to Main

on:
  push:
    branches: [ "[0-9]+.[0-9]+.[0-9]+", "release/**" ]

jobs:
  create-pr:
    runs-on: ${{ vars.OS }}
    steps:
      - uses: actions/checkout@v4

      - name: Get branch name
        id: branch_name
        shell: bash
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Check if PR exists
        id: pr_check
        shell: bash
        run: |
          PR_EXISTS=$(gh pr list --state open --head "${{ env.BRANCH_NAME }}" --json number -q '.[].number')
          if [ -z "$PR_EXISTS" ]; then
            echo "Creating PR to main."
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          else
            echo "PR already exists, skipping creation."
            echo "PR_EXISTS=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        if: env.PR_EXISTS == 'false'
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Pull Request to main
        if: env.PR_EXISTS == 'false'
        shell: bash
        run: |
          PR_TITLE="Merge ${{ env.BRANCH_NAME }} into main"
          gh pr create --base main --head "${{ env.BRANCH_NAME }}" --title "$PR_TITLE" --body "This PR is automatically created from the release branch to the main branch."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pylint:
    runs-on: ${{ vars.OS }}
    needs: create-pr
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        run: |
          pylint --max-line-length=120 --disable=missing-module-docstring,missing-function-docstring,invalid-name,broad-exception-caught,broad-exception-raised,raise-missing-from $(git ls-files '*.py')
