name: Pylint

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main, "[0-9]+.[0-9]+.[0-9]+" ]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ${{ vars.OS }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: Fetch all history for tags

      # Set up python
      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Analysing the code with pylint
      - name: Analysing the code with pylint
        run: |
          pylint --max-line-length=120 --disable=missing-module-docstring,missing-function-docstring,invalid-name,broad-exception-caught,broad-exception-raised,raise-missing-from $(git ls-files '*.py')
