name: Pylint

on:
  push:
    branches: [ main ]
    paths: [ "contigion_utils/**", "tests/**" ]

  pull_request:
    branches: [ main, "[0-9]+.[0-9]+.[0-9]+" ]
    paths: [ "contigion_utils/**", "tests/**" ]

jobs:
  pylint:
    name: Pylint
    runs-on: ${{ vars.OS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pytest
          pip install -r requirements.txt

      - name: Analyse code
        run: |
          pylint --max-line-length=120 --disable=missing-module-docstring,missing-function-docstring,invalid-name,broad-exception-caught,broad-exception-raised,raise-missing-from $(git ls-files '*.py')

  pytest:
    name: Pytest
    runs-on: ${{ vars.OS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install setuptools
          pip install -r requirements.txt

      - name: Run tests
        run: pytest